platform :ios, '14.0'

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Run 'flutter pub get' first."
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        # បង្ខំឱ្យ Library ទាំងអស់ប្រើ Deployment Target 14.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

        # បំបាត់ Flag -G
        cflags = config.build_settings['OTHER_CFLAGS']
        if cflags
          cflags_array = cflags.is_a?(Array) ? cflags : [cflags]
          config.build_settings['OTHER_CFLAGS'] = cflags_array.reject { |f| f == '-G' }
        end
      end
    end
  end
end