platform :ios, '14.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # បង្ខំកាត់ Flag -G ចេញពីគ្រប់ទីកន្លែងសម្រាប់គ្រប់ Target
    target.build_configurations.each do |config|
      config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
      if config.build_settings['OTHER_CFLAGS'].is_a?(Array)
        config.build_settings['OTHER_CFLAGS'].delete('-G')
      else
        config.build_settings['OTHER_CFLAGS'] = config.build_settings['OTHER_CFLAGS'].gsub(/-G/, '')
      end
    end
  end
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end